### ISSUE TITLE
2.7.0 not source compatible (MBEDTLS_DHM_RFC5114_MODP_2048_P)

### ISSUE THREAD

**Issue by keenerd** [ARMmbed/mbedtls#1358]
* OS: linux
* mbedtls 2.7.0

While attempting to build Hiawatha 10.7 against mbedtls 2.7.0 it will fail to find one of the symbols.

    /src/hiawatha-10.7/src/tls.c:348:42: error: ‘MBEDTLS_DHM_RFC5114_MODP_2048_P’ undeclared (first use in this function); did you mean ‘MBEDTLS_DHM_RFC5114_MODP_2048_G’?
       mbedtls_ssl_conf_dh_param(*tls_config, MBEDTLS_DHM_RFC5114_MODP_2048_P, MBEDTLS_DHM_RFC5114_MODP_2048_G);

In 2.6.1 this was defined in `include/mbedtls/dhm.h` and appears to have been removed in commit 784de59 and replaced with `MBEDTLS_DHM_RFC5114_MODP_P`.  This appears to be a typo since the companion variable `MBEDTLS_DHM_RFC5114_MODP_2048_G` did not have its name changed.

**Comment by hardfalcon** [comment]
That change was introduced with commit e2fcfa8, not 784de59 .

**Comment by hanno-arm** [comment]
@keenerd @hardfalcon Thank you for reporting this!
