### ISSUE TITLE
Fails to build with gcc 10.2.1 due to -Wformat-signedness

### ISSUE THREAD

**Issue by jirutka** [ARMmbed/mbedtls#3957]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS|linux

**mbed TLS build:**  
Version: 2.25.0
OS version: Alpine Edge
Configuration: default with `MBEDTLS_THREADING_C` and `MBEDTLS_THREADING_PTHREAD` enabled
Compiler and options:
```
gcc 10.2.1 (pre-release 20201203)
CFLAGS="-Os -fomit-frame-pointer"
CMAKE_BUILD_TYPE="MinSizeRel"
USE_SHARED_MBEDTLS_LIBRARY=ON
```

Additional environment information:  

Architecture: x86_64

**Expected behavior**   

Should build successfully.

**Actual behavior**  

```
cd ./programs/ssl && /usr/bin/cc  -I./programs/ssl/../../tests/include -I./include -Os -fomit-frame-pointer -Wno-format-signedness -Wall -Wextra -Wwrite-strings -Wvla -Wlogical-op -Wshadow -Wformat-signedness -Werror -Os -DNDEBUG -o CMakeFiles/ssl_client2.dir/__/test/query_config.c.o -c ./programs/test/query_config.c
./programs/ssl/ssl_pthread_server.c: In function 'handle_ssl_connection':
./programs/ssl/ssl_pthread_server.c:144:79: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'int' [-Werror=format=]
  144 |         mbedtls_printf( "  [ #%ld ]  failed: mbedtls_ssl_setup returned -0x%04x\n",
      |                                                                            ~~~^
      |                                                                               |
      |                                                                               unsigned int
      |                                                                            %04x
  145 |                 thread_id, -ret );
      |                            ~~~~                                                
      |                            |
      |                            int
./programs/ssl/ssl_pthread_server.c:160:87: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'int' [-Werror=format=]
  160 |             mbedtls_printf( "  [ #%ld ]  failed: mbedtls_ssl_handshake returned -0x%04x\n",
      |                                                                                    ~~~^
      |                                                                                       |
      |                                                                                       unsigned int
      |                                                                                    %04x
  161 |                     thread_id, -ret );
      |                                ~~~~                                                    
      |                                |
      |                                int
./programs/ssl/ssl_pthread_server.c:197:82: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'int' [-Werror=format=]
  197 |                     mbedtls_printf( "  [ #%ld ]  mbedtls_ssl_read returned -0x%04x\n",
      |                                                                               ~~~^
      |                                                                                  |
      |                                                                                  unsigned int
      |                                                                               %04x
  198 |                             thread_id, -ret );
      |                                        ~~~~                                       
      |                                        |
      |                                        int
./programs/ssl/ssl_pthread_server.c:231:83: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'int' [-Werror=format=]
  231 |             mbedtls_printf( "  [ #%ld ]  failed: mbedtls_ssl_write returned -0x%04x\n",
      |                                                                                ~~~^
      |                                                                                   |
      |                                                                                   unsigned int
      |                                                                                %04x
  232 |                     thread_id, ret );
      |                                ~~~                                                 
      |                                |
      |                                int
./programs/ssl/ssl_pthread_server.c:248:90: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'int' [-Werror=format=]
  248 |             mbedtls_printf( "  [ #%ld ]  failed: mbedtls_ssl_close_notify returned -0x%04x\n",
      |                                                                                       ~~~^
      |                                                                                          |
      |                                                                                          unsigned int
      |                                                                                       %04x
  249 |                     thread_id, ret );
      |                                ~~~                                                        
      |                                |
      |                                int
./programs/ssl/ssl_pthread_server.c:265:59: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'int' [-Werror=format=]
  265 |         mbedtls_printf("  [ #%ld ]  Last error was: -0x%04x - %s\n\n",
      |                                                        ~~~^
      |                                                           |
      |                                                           unsigned int
      |                                                        %04x
  266 |                thread_id, -ret, error_buf );
      |                           ~~~~                             
      |                           |
      |                           int
./programs/ssl/ssl_pthread_server.c: In function 'main':
./programs/ssl/ssl_pthread_server.c:410:72: error: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'int' [-Werror=format=]
  410 |         mbedtls_printf( " failed: mbedtls_ctr_drbg_seed returned -0x%04x\n",
      |                                                                     ~~~^
      |                                                                        |
      |                                                                        unsigned int
      |                                                                     %04x
  411 |                 -ret );
      |                 ~~~~                                                    
      |                 |
      |                 int
./programs/ssl/ssl_pthread_server.c:427:78: error: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'int' [-Werror=format=]
  427 |         mbedtls_printf( " failed: mbedtls_ssl_config_defaults returned -0x%04x\n",
      |                                                                           ~~~^
      |                                                                              |
      |                                                                              unsigned int
      |                                                                           %04x
  428 |                 -ret );
      |                 ~~~~                                                          
      |                 |
      |                 int
./programs/ssl/ssl_pthread_server.c:473:60: error: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'int' [-Werror=format=]
  473 |         mbedtls_printf( "  [ main ]  Last error was: -0x%04x - %s\n", -ret, error_buf );
      |                                                         ~~~^          ~~~~
      |                                                            |          |
      |                                                            |          int
      |                                                            unsigned int
      |                                                         %04x
Scanning dependencies of target dtls_server
./programs/ssl/ssl_pthread_server.c:485:79: error: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'int' [-Werror=format=]
  485 |         mbedtls_printf( "  [ main ] failed: mbedtls_net_accept returned -0x%04x\n", ret );
      |                                                                            ~~~^     ~~~
      |                                                                               |     |
      |                                                                               |     int
      |                                                                               unsigned int
      |                                                                            %04x
```

**Steps to reproduce**

Run on Alpine Linux (edge):

```
export CFLAGS="-Os -fomit-frame-pointer"

sed -i \
        -e 's|//\(#define MBEDTLS_THREADING_C\)|\1|' \
        -e 's|//\(#define MBEDTLS_THREADING_PTHREAD\)|\1|' \
        include/mbedtls/config.h

cmake . \
        -DCMAKE_BUILD_TYPE="MinSizeRel" \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_VERBOSE_MAKEFILE=ON \
        -DUSE_SHARED_MBEDTLS_LIBRARY=ON
make
```

Related issues and pull requests: #3579 #1534 #3153

**Comment by gilles-peskine-arm** [comment]
This should be fixed by https://github.com/ARMmbed/mbedtls/pull/3579.
