### ISSUE TITLE
2.26.0 fails to build with cmake "release" and GCC 9.3

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#4233]
Steps to reproduce:
```
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE:String=Release ..
make
```
Error messages:
```
/home/manpeg01/src/mbedtls/library/x509.c: In function ‘mbedtls_x509_dn_gets’:
/home/manpeg01/src/mbedtls/library/x509.c:789:40: error: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 1 [-Werror=format-truncation=]
  789 |         ret = mbedtls_snprintf( p, n, "%s", s );
      |                                        ^~   ~
In file included from /usr/include/stdio.h:867,
                 from /home/manpeg01/src/mbedtls/include/mbedtls/bignum.h:35,
                 from /home/manpeg01/src/mbedtls/include/mbedtls/asn1.h:34,
                 from /home/manpeg01/src/mbedtls/include/mbedtls/x509.h:31,
                 from /home/manpeg01/src/mbedtls/library/x509.c:34:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin_snprintf’ output between 1 and 256 bytes into a destination of size 1
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/manpeg01/src/mbedtls/library/x509.c: In function ‘mbedtls_x509_serial_gets’:
/home/manpeg01/src/mbedtls/library/x509.c:827:41: error: ‘....’ directive output truncated writing 4 bytes into a region of size 1 [-Werror=format-truncation=]
  827 |         ret = mbedtls_snprintf( p, n, "...." );
      |                                        ~^~~
In file included from /usr/include/stdio.h:867,
                 from /home/manpeg01/src/mbedtls/include/mbedtls/bignum.h:35,
                 from /home/manpeg01/src/mbedtls/include/mbedtls/asn1.h:34,
                 from /home/manpeg01/src/mbedtls/include/mbedtls/x509.h:31,
                 from /home/manpeg01/src/mbedtls/library/x509.c:34:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin_snprintf’ output 5 bytes into a destination of size 1
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/manpeg01/src/mbedtls/library/x509.c: In function ‘mbedtls_x509_sig_alg_gets’:
/home/manpeg01/src/mbedtls/library/x509.c:864:41: error: ‘ (’ directive output truncated writing 2 bytes into a region of size 1 [-Werror=format-truncation=]
  864 |         ret = mbedtls_snprintf( p, n, " (%s, MGF1-%s, 0x%02X)",
      |                                        ~^
/home/manpeg01/src/mbedtls/library/x509.c:864:39: note: assuming directive output of 3 bytes
  864 |         ret = mbedtls_snprintf( p, n, " (%s, MGF1-%s, 0x%02X)",
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~
/home/manpeg01/src/mbedtls/library/x509.c:864:39: note: assuming directive output of 3 bytes
/home/manpeg01/src/mbedtls/library/x509.c:864:39: note: using the range [0, 4294967295] for directive argument
In file included from /usr/include/stdio.h:867,
                 from /home/manpeg01/src/mbedtls/include/mbedtls/bignum.h:35,
                 from /home/manpeg01/src/mbedtls/include/mbedtls/asn1.h:34,
                 from /home/manpeg01/src/mbedtls/include/mbedtls/x509.h:31,
                 from /home/manpeg01/src/mbedtls/library/x509.c:34:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output 17 or more bytes (assuming 23) into a destination of size 1
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
GCC version: 9.3.0
Environment: Ubuntu 20.04

I didn't investigate so far. Cc @paul-elliott-arm as you're probably more familiar with this.

**Comment by eXhumer** [comment]
I also encountered this issue. This is because of [this commit](https://github.com/ARMmbed/mbedtls/commit/21c62a2aede0014e266c9bd9add0734c5a68c0da). Reverting back this fixes the issue for me.
