### PR TITLE
fix build with gcc 4.8

### PR DESCRIPTION
**Pull request by ffontaine**
Fix the following build failure with gcc 4.8:

```
/usr/lfs/hdd_v1/rc-buildroot-test/scripts/instance-0/output-1/build/mbedtls-2.28.0/library/bignum.c: In function 'mpi_select':
/usr/lfs/hdd_v1/rc-buildroot-test/scripts/instance-0/output-1/build/mbedtls-2.28.0/library/bignum.c:1994:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for( size_t i = 0; i < T_size; i++ )
     ^
/usr/lfs/hdd_v1/rc-buildroot-test/scripts/instance-0/output-1/build/mbedtls-2.28.0/library/bignum.c:1994:5: note: use option -std=c99 or -std=gnu99 to compile your code
```

Fixes:
 - http://autobuild.buildroot.org/results/56ac0a8726d09eed8f45f865934fa7781a0e667a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by yanesca** [comment]
Hi @ffontaine, thank you very much for contributing.

It looks like that the original code is valid C99. Mbed TLS is using C99 since version 2.18. Even if we accept this change, it wouldn't make much difference in the long term as we are accepting C99 constructs in new contributions.

I am closing this PR for now, but please feel free to reply to discuss it. We can still reopen this if it turns out that I misjudged the nature of the issue.
