### ISSUE TITLE
compiler frame pointers causes compilation fault in mbedtls

### ISSUE THREAD

**Issue by mottigondabi** [ARMmbed/mbedtls#426]
In debug mode the compiler uses frame pointers more heavily, even when they're not needed. what's worse, it uses them on naked asm functions. if those inline asm uses `r7` explicitly or clobber it, then you'll have the following error message:
**/home/fw/mottig/work/git/provisioning/out/k64f_mbed_gnuc-debug/build_yotta/yotta_modules/mbedtls/source/bignum.c: In function 'mpi_mul_hlp':
/home/fw/mottig/work/git/provisioning/out/k64f_mbed_gnuc-debug/build_yotta/yotta_modules/mbedtls/source/bignum.c:1134:1: error: r7 cannot be used in asm here
}
^
**

**Comment by mpg** [comment]
That's fixed in the development branch on github. For earlier versions, the workaround is to manually disable `MBEDTLS_HAVE_ASM` for debug builds - see [here](https://github.com/ARMmbed/mbedtls/blob/development/yotta/data/README.md#configuring-mbed-tls-features) for how to do that when building with yotta.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-646

**Comment by sbutcher-arm** [comment]
@mottigondabi - Can you please confirm the most recent version works for you (or the workaround does), and I'll close this issue.

**Comment by mottigondabi** [comment]
@sbutcher-arm - Working with v2.2.0 with patch.cmake file to override this issue (until formal version will be published):

if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
	set_source_files_properties(
		"{PATH_TO_YT_MODULE}/mbedtls/source/bignum.c"
		PROPERTIES COMPILE_FLAGS -fomit-frame-pointer)
endif()
